version: '3.9'

services:
  web:
    build: .
    container_name: mysite_local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
